cloud:
  aws:
    stack:
      auto: false
    region:
      static: ${AWS_S3_REGION}
    credentials:
      access-key: ${AWS_S3_ACCESS_KEY_ID}
      secret-key: ${AWS_S3_SECRET_ACCESS_KEY}

aws:
  s3:
    image:
      bucket: ${AWS_S3_BUCKET}

