name: SpringBoot with Gradle CI / CD

on:
  push:
    branches: [ stage ]
  pull_request:
    branches: [ stage ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Make Directory for CI
        run: mkdir deploy

      - name: Copy Jar
        run: cp ./build/libs/*.jar ./deploy/

      - name: Copy Appspec
        run: cp appspec.yml ./deploy/

      - name: Copy scripts
        run: cp ./scripts/* ./deploy/

      - name: Make zip file
        run: zip -r -qq -j ./career-zip-api-build.zip ./deploy/

      - name: Deliver to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
          --region ap-northeast-2 \
          --acl private \
          ./career-zip-api-build.zip s3://career-zip-stage-api/

      - name: Codedeploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws deploy create-deployment \
          --application-name career-zip-stage-codedeploy \
          --deployment-group-name career-zip-stage-codedeploy-group \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=career-zip-stage-api,bundleType=zip,key=career-zip-api-build.zip \
          --region ap-northeast-2
